CREATE TABLE users (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    username VARCHAR2(50),
    user_id VARCHAR2(50) UNIQUE,
    password VARCHAR2(50),
    interests VARCHAR2(300),
    PRIMARY KEY (id)
);